//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetDefinitionMachineTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDef
    {
        public decimal ad_id { get; set; }
        public string ad_name { get; set; }
        public Nullable<decimal> ad_type_id { get; set; }
        public string ad_class { get; set; }
    
        public virtual Assettype Assettype { get; set; }
    }
}
